# kubectl apply -f k8s/provisioner.yaml

# When you just getting started with Karpenter, it's a good idea to check logs in case you get any errors.
# kubectl logs -f -n karpenter \
# -l app.kubernetes.io/name=karpenter

# In another window, let's run get pods.
# watch -n 1 -t kubectl get pods

# Then let's get all the nodes available in the Kubernetes cluster.
# watch -n 1 -t kubectl get nodes

# Finally, create the deployment with 5 replicas.
# kubectl apply -f k8s/deployment.yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          requests:
            cpu: "4"
            memory: 4Gi
        ports:
        - containerPort: 80
